import React from 'react';

const NotFound = () => {
    return (
        <div>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
            <h1 style={{display: 'inline-block'}}>404</h1>
        </div>
    );
};

export default NotFound;